spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
         - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
server:
  port: ${app_port}
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka