server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
         - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka