
# application.yml file of the config server (Spring Cloud Config Server)
server:
  port: 8081 # or whatever
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          #uri: file:///path/to/your/config/dir
          uri: git@github.com:DavPz/microservicios-tutorial.git
          # This allows us to use client service names (i.e. application names) as sub-directories in the config repository. See below example.
          clone-on-start: true
          delete-untracked-branches: true
          ignore-local-ssh-settings: false
          refresh-rate: 10
          default-label: 'gateway'
          search-paths: 'config-data' 