server:
  port: 8081
spring:
  cloud:     
    config:
      server:
        git:
          default-label: cricuit-breaker
          uri: https://github.com/DavPz/microservicios-tutorial.git
          search-paths: config-data
  application:
    name: config-service